config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get 'home/about' => 'homes#about'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :books
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!

  def index
  	@users = User.all
  	@user = current_user
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  	@newbook = Book.new
  	@user = current_user
  end

  def edit
  	book = Book.find(params[:id])
  	if book.user == current_user
  		@book = Book.find(params[:id])
  	else
  		redirect_to books_path
  	end
  end
  
  def create
  	@book = Book.new(book_params) #index view in create action
  	@book.user_id = current_user.id
  	if @book.save
  		@user = current_user
  		flash[:notice] = "You have created book successfully."
  		redirect_to book_path(@book.id)
  	else
  		@users = User.all
  		@user = current_user
  		@user.introduction = current_user.introduction
  		@books = Book.all
  		flash[:notice] = "error"
  		render action: :index
  	end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		flash[:notice] = "Book was successfully updated."
  		redirect_to book_path(@book.id)
  	else
  		flash[:notice] = "error"
  		render action: :edit
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	flash[:notice] = "Book was successfully destroyed."
  	redirect_to books_path
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

  def user_params
	  params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<main>
	<p id="notice"><%= notice %></p>
	<div class="container px-5 px-sm-0">
		<div class="row">
			<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
				<h1>Editing Book</h1>
				<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>

					<% if @book.errors.any? %>
						<div class=“alert alert-warning”>
						  <ul>
							<% @book.errors.full_messages.each do |message| %>
								<li><%= message %></li>
							<% end %>
						  </ul>
						</div>
					<% end %>
					<div class="form-group">
						<label for="book_title">Title</label>
						<%= f.text_field :title, class: "form-control book_title" %>
					</div>
					<div class="form-group">
						<label for="book_opinion">Opinion</label>
						<%= f.text_area :body, class: "form-control book_opinion" %>
					</div>
					<div class="form-group">
					  <%= f.submit "Update Book", class:"btn btn-success" %>
					</div>
				<% end %>

				<p>
				  <u><%= link_to 'Show', book_path(@book.id) %></u>
				  |
				  <u><%= link_to 'Back', books_path %></u>
				</p>
			</div>
		</div>
	</div>
</main>

app/views/books/index.html.erb
<main>
	<p id="notice"><%= notice %></p>
	<div class="container px-5 px-sm-0">
		<div class="row">
			<div class="col-md-3">
				<h2>User info</h2>
				<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
				<table class="table">
				  <tbody>
				  	<tr></tr>
				  	<tr>
				  	  <th>name</th>
				  	  <th><%= @user.name %></th>
				  	</tr>
				  	<tr>
				  	  <th>introduction</th>
				  	  <th><%= @user.introduction %></th>
				  	</tr>
				  </tbody>
				 </table>
				 <div class="row">
					 	<%= link_to "", edit_user_path(@user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
				 </div>

				 <h2 class="mt-3">New book</h2>
				 <%= form_for(@book, url: '/books') do |f| %>
					<% if @book.errors.any? %>
						<div class=“alert alert-warning”>
							<ul>
							  <% @book.errors.full_messages.each do |message| %>
							    <li><%= message %></li>
							  <% end %>
							</ul>
						</div>
					<% end %>
					<div class="form-group">
						<label for="book_title">Title</label>
						<%= f.text_field :title, class: "form-control book_title" %>
					</div>
					<div class="form-group">
						<label for="book_opinion">Opinion</label>
						<%= f.text_area :body, class: "form-control book_opinion" %>
					</div>
					<%= f.submit "Create Book", class:"btn btn-success" %>
				<% end %>
			</div>

			<div class="col-md-8 offset-md-1">
				<h2>Books</h2>
				<table class="table table-hover table-inverse">
					<thead>
					  <tr>
					  	<th></th>
					  	<th>Title</th>
					  	<th>Opinion</th>
					  </tr>
					</thead>
					<tbody>

						  <% @books.each do |book| %>
							  <tr>
							  	<td>
							  		<%= link_to user_path(book.user_id) do %>
								  		<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg",size:'40x40' %>
								  	<% end %>
								</td>
								<td>
								  <%= link_to book_path(book.id) do %>
								    <%= book.title %>
								  <% end %>
								</td>
								<td>
								  <%= book.body %>
								</td>
							  </tr>
						  <% end %>

					</tbody>
				</table>
			</div>
		</div>
	</div>
</main>

app/views/books/show.html.erb
<main>
	<p id="notice"><%= notice %></p>
	<div class="container px-5 px-sm-0">
		<div class="row">
			<div class="col-md-3">
				<h2>User info</h2>
				<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
				<table class="table">
				  <tbody>
				  	<tr></tr>
				  	<tr>
				  	  <th>name</th>
				  	  <th><%= @book.user.name %></th>
				  	</tr>
				  	<tr>
				  	  <th>introduction</th>
				  	  <th><%= @book.user.introduction %></th>
				  	</tr>
				  </tbody>
				 </table>
				 <div class="row">
				   <%= link_to "", edit_user_path(@book.user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
				 </div>

				 <h2 class="mt-3">New book</h2>
				 <%= form_for(@newbook) do |f| %>
					<% if @book.errors.any? %>
						<div class=“alert alert-warning”>
							<ul>
							  <% @book.errors.full_messages.each do |message| %>
							    <li><%= message %></li>
							  <% end %>
							</ul>
						</div>
					<% end %>
					<div class="form-group">
						<label for="book_title">Title</label>
						<%= f.text_field :title, class: "form-control book_title" %>
					</div>
					<div class="form-group">
						<label for="book_opinion">Opinion</label>
						<%= f.text_area :body, class: "form-control book_opinion" %>
					</div>
					<%= f.submit "Create Book", class:"btn btn-success" %>
				<% end %>
			</div>

			<div class="col-md-8 offset-md-1">
				<h2>Book detail</h2>
				<table class="table table-hover table-inverse">
					<tbody>
						<%= form_for(@book) do |f| %>
						  <tr>
						  	<td>
						  	  <%= link_to user_path(@book.user_id) do %> <!-- jump to users/:id(show) page -->
								    <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg",size:'40x40' %><br />
								    <%= @book.user.name %>
							    <% end %>
							</td>
							<td>
						  	  <%= link_to book_path do %> <!-- jump to books/:id(show) page -->
								<%= @book.title %>
							  <% end %>
							</td>
							<td>
								<%= @book.body %>
							</td>

							<% if @book.user_id == current_user.id %>
								<td>
								  <%= link_to edit_book_path do %>
								  	<i class="btn-sm btn-success">Edit</i>
								  <% end %>
								</td>
								<td>
								  <%= link_to book_path, method: :delete do %>
								  	<i class="btn-sm btn-danger">Destroy</i>
								  <% end %>
								</td>
							<% end %>

						  </tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</main>