config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  get 'home/about' => 'homes#about'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :books
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookers2</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'> 
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Users", users_path, class: "fas fa-users nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "logout", destroy_user_session_path, class: "fas fa-sign-out-alt nav-link text-light", method: :delete %>
                </li>
    
              <% else %>
    
                <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
                <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
                <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>
                <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>
    
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>